[package]
name = "void_db"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
async-trait.workspace = true
gpui.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
serial_test.workspace = true
simplelog.workspace = true
surrealdb.workspace = true
thiserror.workspace = true
tokio = "1.47.1"
void_core.workspace = true
