server: panel.void-project.ru:443

auth: GhostOfMyDream

obfs:
  type: salamander
  salamander:
    password: GhostOfMyDream

tls:
  insecure: true

bandwidth:
  up: 20 mbps
  down: 600 mbps

socks5:
  listen: 127.0.0.1:1080

http:
  listen: 127.0.0.1:8080

masquerade:
  type: none

transport:
  type: udp 
  udp:
    hopInterval: 30s
