[package]
name = "void_app"
version = "0.1.0"
edition = "2024"
license.workspace = true

[package.metadata.bundle]
name = "VOID"
identifier = "org.transhumanist.void"
version = "0.1.0"

[[bin]]
name = "VOID"
path = "src/main.rs"

[dependencies]
gpui.workspace = true
void_components.workspace = true
void_db = { path = "../void_db" }
