name: Build

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'src-tauri/**'
      - 'tests/**'
      - 'package_lock.json'
      - 'src-tauri/Cargo.lock'
      - '.github/workflows/test-build.yml'
  pull_request:
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: true

    runs-on: 'ubuntu-24.04'
    steps:
      - uses: actions/checkout@v4

      - name: Setup NPM
        uses: actions/setup-node@v3.9.1
        with:
          node-version: 'latest'        
      - run: npm i

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install dependencies
        run: |
          sudo apt update
          sudo apt install libwebkit2gtk-4.1-dev \
          build-essential \
          curl \
          wget \
          file \
          libxdo-dev \
          libssl-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev\
          gcc-14 g++-14
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100 \
            --slave /usr/bin/g++ g++ /usr/bin/g++-14

      - name: Build Tauri
        run: npm run tauri build
